In [1]:
import numpy as np
from nnlib.activation_functions.relu import ReLu
from nnlib.activation_functions.leaky_relu import LeakyReLu
from nnlib.activation_functions.linear import Linear
from nnlib.activation_functions.sigmoid import Sigmoid
from nnlib.activation_functions.tanh import Tanh

In [2]:
'''
Test ReLu activation function

This code snippet demonstrates the usage of the ReLu (Rectified Linear Unit) activation function. 
The ReLu activation is a widely used activation function in neural networks and is defined as 
f(x) = max(0, x), where x is the input.

Usage:
- Create a ReLu activation function object using the `relu.ReLu()` constructor.
- Activate a sample input value (e.g., 0.5) using the `activate()` method and print the result.

Example:
    activation = relu.ReLu()  # Create a ReLu activation function
    result = activation.activate(0.5)  # Activate the input value 0.5
    print(result)  # Print the result of the ReLu activation

This code snippet serves as a basic test of the ReLu activation function by applying it to a 
single input value and displaying the output.
'''
activation = ReLu()
input_value = np.array([-1.0,-0.5,0,0.5,1.0])
forward_result = activation.activate(input_value)
backward_result = activation.derivate(input_value)
print("Input value: {}".format(input_value))
print("Forward result: {}".format(forward_result))
print("Backward result: {}".format(backward_result))

Input value: [-1.  -0.5  0.   0.5  1. ]
Forward result: [0.  0.  0.  0.5 1. ]
Backward result: [0 0 0 1 1]


In [3]:
'''
Test Leaky ReLu activation function

This code snippet demonstrates the usage of the Leaky ReLu (Rectified Linear Unit) activation function. 
The Leaky ReLu activation is a variant of ReLu that allows a small, non-zero gradient for negative inputs, 
preventing neurons from dying during training. It is defined as:
f(x) = x if x > 0
f(x) = alpha * x if x <= 0
where alpha is a small positive constant.

Usage:
- Create a Leaky ReLu activation function object using the `leaky_relu.LeakyReLu()` constructor.
- Activate a sample input value (e.g., 0.5) using the `activate()` method and print the result.

Example:
    activation = leaky_relu.LeakyReLu()  # Create a Leaky ReLu activation function
    input_value = 0.5
    forward_result = activation.activate(input_value)  # Activate the input value 0.5
    print("Input value: {}".format(input_value))
    print("Forward result: {}".format(forward_result))

This code snippet serves as a basic test of the Leaky ReLu activation function by applying it to a 
single input value and displaying the output, both in the forward and backward passes.
'''
activation = LeakyReLu(0.01)
input_value = np.array([-1.0,-0.5,0,0.5,1.0])
forward_result = activation.activate(input_value)
backward_result = activation.derivate(input_value)
print("Input value: {}".format(input_value))
print("Forward result: {}".format(forward_result))
print("Backward result: {}".format(backward_result))


Input value: [-1.  -0.5  0.   0.5  1. ]
Forward result: [-0.01  -0.005  0.     0.5    1.   ]
Backward result: [0.01 0.01 0.01 1.   1.  ]


In [4]:
'''
Test Linear activation function

This code snippet demonstrates the usage of the Linear activation function. The Linear activation function
simply returns the input value without introducing non-linearity. It is defined as f(x) = x, where x is the input.

Usage:
- Create a Linear activation function object using the `linear.Linear()` constructor.
- Activate a sample input value (e.g., 0.5) using the `activate()` method and print the result.

Example:
    activation = linear.Linear()  # Create a Linear activation function
    input_value = 0.5
    forward_result = activation.activate(input_value)  # Activate the input value 0.5
    print("Input value: {}".format(input_value))
    print("Forward result: {}".format(forward_result))

This code snippet serves as a basic test of the Linear activation function by applying it to a 
single input value and displaying the output, both in the forward and backward passes.
'''
activation = Linear()
input_value = np.array([-1.0,-0.5,0,0.5,1.0])
forward_result = activation.activate(input_value)
backward_result = activation.derivate(input_value)
print("Input value: {}".format(input_value))
print("Forward result: {}".format(forward_result))
print("Backward result: {}".format(backward_result))


Input value: [-1.  -0.5  0.   0.5  1. ]
Forward result: [-1.  -0.5  0.   0.5  1. ]
Backward result: [1. 1. 1. 1. 1.]


In [5]:
'''
Test Sigmoid activation function

This code snippet demonstrates the usage of the Sigmoid activation function. 
The Sigmoid activation function maps input values to the range (0, 1) and is commonly used in 
neural networks for introducing non-linearity.

Usage:
- Create a Sigmoid activation function object using the `sigmoid.Sigmoid()` constructor.
- Activate a sample input value (e.g., 0.5) using the `activate()` method and print the result.

Example:
    activation = sigmoid.Sigmoid()  # Create a Sigmoid activation function
    input_value = 0.5
    forward_result = activation.activate(input_value)  # Activate the input value 0.5
    print("Input value: {}".format(input_value))
    print("Forward result: {}".format(forward_result))

This code snippet serves as a basic test of the Sigmoid activation function by applying it to a 
single input value and displaying the output, both in the forward and backward passes.
'''
activation = Sigmoid()
input_value = np.array([-1.0,-0.5,0,0.5,1.0])
forward_result = activation.activate(input_value)
backward_result = activation.derivate(input_value)
print("Input value: {}".format(input_value))
print("Forward result: {}".format(forward_result))
print("Backward result: {}".format(backward_result))


Input value: [-1.  -0.5  0.   0.5  1. ]
Forward result: [0.26894142 0.37754067 0.5        0.62245933 0.73105858]
Backward result: [0.19661193 0.23500371 0.25       0.23500371 0.19661193]


In [6]:
'''
Test Tanh activation function

This code snippet demonstrates the usage of the Hyperbolic Tangent (Tanh) activation function. 
The Tanh activation function maps input values to the range (-1, 1) and is commonly used in 
neural networks for introducing non-linearity.

Usage:
- Create a Tanh activation function object using the `tanh.Tanh()` constructor.
- Activate a sample input value (e.g., 0.5) using the `activate()` method and print the result.

Example:
    activation = tanh.Tanh()  # Create a Tanh activation function
    input_value = 0.5
    forward_result = activation.activate(input_value)  # Activate the input value 0.5
    print("Input value: {}".format(input_value))
    print("Forward result: {}".format(forward_result))

This code snippet serves as a basic test of the Tanh activation function by applying it to a 
single input value and displaying the output, both in the forward and backward passes.
'''
activation = Tanh()
input_value = np.array([-1.0,-0.5,0,0.5,1.0])
forward_result = activation.activate(input_value)
backward_result = activation.derivate(input_value)
print("Input value: {}".format(input_value))
print("Forward result: {}".format(forward_result))
print("Backward result: {}".format(backward_result))


Input value: [-1.  -0.5  0.   0.5  1. ]
Forward result: [-0.76159416 -0.46211716  0.          0.46211716  0.76159416]
Backward result: [0.41997434 0.78644773 1.         0.78644773 0.41997434]


In [7]:
from nnlib.initialization_functions.he import He
from nnlib.initialization_functions.xavier import Xavier
from nnlib.initialization_functions.uniform import Uniform
from nnlib.initialization_functions.normal import Normal

he_weight_init = He()
xavier_weight_init = Xavier()
uniform_weight_init = Uniform()
normal_weight_init = Normal()

print("He weight init: {}".format(he_weight_init.initialize_weights(10, 10)))
print("Xavier weight init: {}".format(xavier_weight_init.initialize_weights(10, 10)))
print("Uniform weight init: {}".format(uniform_weight_init.initialize_weights(10, 10)))
print("Normal weight init: {}".format(normal_weight_init.initialize_weights(10, 10)))


He weight init: [[-0.23833209 -0.04401495  0.00761981  0.62542551 -0.43188039  0.22306338
  -1.01732689  0.71327879 -0.04931432 -0.01654384]
 [-0.19910085 -0.24994597  0.02072512  0.42806518 -0.06218941 -0.51912847
  -0.7067272   0.17574918 -0.540315   -0.20121373]
 [ 0.5727702   0.36076912 -0.22914252  0.04408876 -0.40457042  0.11427702
   0.35243471  0.43815808  0.06592693  0.94569932]
 [-0.28227588  0.06352193 -0.12042599  0.40260983  0.32438738 -0.26929012
  -0.05096352  0.51853177  0.35187066  0.74085559]
 [-0.92047376  0.14320951  0.87127444  0.53270104  0.37529183 -0.07070329
  -0.07958926  0.4212114   0.26332307  0.29726388]
 [-0.10390607  0.69303542  0.44508955 -0.26245523  0.64803126  0.2972754
   0.42720356  0.1510913  -0.05681497 -0.20051583]
 [-0.68381542  0.33545304 -0.99985011  0.6579545   0.54645644  0.2404405
  -0.08446474  0.70475943 -0.37331446  0.18533105]
 [-0.0745402  -1.11220568  0.24577602  0.02478703  0.40976084  0.0365391
  -0.16485022 -0.46297492  0.75974156 

In [8]:
from nnlib.loss_functions.mse import MeanSquaredError
from nnlib.loss_functions.bce import BinaryCrossEntropyLoss


mse_loss = MeanSquaredError()
bce_loss = BinaryCrossEntropyLoss()

print("MeanSquaredError loss: {}".format(mse_loss.compute(np.array([0.5, 0.5]), np.array([0.4, 0.5]))))
print("BinaryCrossEntropyLoss loss: {}".format(bce_loss.compute(np.array([0, 1]), np.array([1, 1]))))

MeanSquaredError loss: 0.0049999999999999975
BinaryCrossEntropyLoss loss: 17.269388197455342


In [9]:
from nnlib.layers.dense import Dense
import numpy as np

# Initialize a Dense layer
input_dim = 3  # Number of input features
n_units = 3    # Number of units in the Dense layer

dense_layer = Dense(n_units=n_units, 
                    activation=Sigmoid(),
                    input_dim=input_dim)

# Initialize weights and biases manually for testing
weights = He().initialize_weights(n_units, input_dim)
print(weights)
biases = np.array([[0.1, 0.2, 0.3],
                   [0.3, 0.4, 0.6],
                   [0.5, 0.6, 0.2]])

dense_layer.set_weights({'weights': weights, 'biases': biases})

# Perform a forward pass
input_data = np.array([[0.5, 0.6, 0.4],
                       [0.2, 0.1, 0.8],
                       [0.3, 0.4, 0.3]])
output_data = dense_layer.forward(input_data)

print("Forward pass output:")
print(output_data)
print(f'mse_loss: {mse_loss.compute(np.array([1, 0.5, 1]), output_data)}')

# Perform a backward pass
dLda = mse_loss.derivate(np.array([1, 0.5, 1]), output_data)
dLda_prev = dense_layer.backward(dLda)

print("\nBackward pass output (dLda_prev):")
print(dLda_prev)


[[ 1.12600991  0.77886974  0.68657136]
 [ 0.14302143  0.48831309 -0.89481576]
 [ 0.76071747  0.19475219 -1.14572713]]
Forward pass output:
[[0.74137066 0.72318659 0.41292305]
 [0.7591597  0.68144209 0.43321424]
 [0.75458676 0.74789404 0.42661558]]
mse_loss: 0.14710899054960602

Backward pass output (dLda_prev):
[[-0.2375009   0.28414653  0.26807004]
 [-0.22890922  0.27493102  0.26724411]
 [-0.22213332  0.2836584   0.27045623]]


In [10]:
from nnlib.optimization_functions.sgd import StochastciGradientDescent

# Initialize a Dense layer
input_dim = 3  # Number of input features
n_units = 3    # Number of units in the Dense layer

dense_layer = Dense(n_units=n_units, 
                    activation=Sigmoid(),
                    input_dim=input_dim)

# Initialize weights and biases manually for testing
weights = He().initialize_weights(input_dim, n_units)
biases = He().initialize_bias(n_units)

dense_layer.set_weights({'weights': weights, 'biases': biases})

# Perform a forward pass
input_data = np.array([[0.5, 0.6, 0.7]])
output_data = dense_layer.forward(input_data)

print("input Data:")    
print(input_data)

print("Initial Weights:")
print(weights)

print("Initial Biases: ")
print(biases)

print("Forward pass output: ")
print(output_data)

# Assuming mse_loss is defined elsewhere
# print(f'mse_loss: {mse_loss.compute(np.array([1, 0.5, 1]), output_data)}')

# Perform a backward pass
# Dummy derivative of the loss with respect to the activation
dLda = np.array([[0.1, -0.1, 0.2]])  
dLda_prev = dense_layer.backward(dLda)

print("\nBackward pass output (dLda_prev):")
print(dLda_prev)

# Initialize SGD optimizer and update the Dense layer's parameters
sgd_optimizer = StochastciGradientDescent(learning_rate=0.01)
sgd_optimizer.update(dense_layer)

# Check the updated weights and biases
updated_weights, updated_biases = dense_layer.get_weights()['weights'], dense_layer.get_weights()['biases']
print("\nUpdated weights:")
print(updated_weights)
print("\nUpdated biases:")
print(updated_biases)

input Data:
[[0.5 0.6 0.7]]
Initial Weights:
[[ 0.7447731  -0.30910493 -0.49720424]
 [-0.4062474  -1.23738879 -1.03115752]
 [-1.49354541  1.07231566 -0.40553674]]
Initial Biases: 
[[0. 0. 0.]]
Forward pass output: 
[[0.28560145 0.46347399 0.24027501]]

Backward pass output (dLda_prev):
[[ 0.00473001 -0.01516527 -0.0719437 ]]

Updated weights:
[[ 0.74467108 -0.3089806  -0.49738679]
 [-0.40636982 -1.23723959 -1.03137657]
 [-1.49368824  1.07248972 -0.4057923 ]]

Updated biases:
[[-0.00020403  0.00024867 -0.00036509]]


In [11]:
import numpy as np
import pickle

# Dummy classes for testing
from nnlib.layers.dense import Dense

from nnlib.activation_functions.linear import Linear
from nnlib.activation_functions.sigmoid import Sigmoid
from nnlib.activation_functions.relu import ReLu

from nnlib.optimization_functions.adam import AdaptiveMomentEstimation

from nnlib.models.sequential import SequentialModel

from nnlib.loss_functions.mse import MeanSquaredError

from nnlib.initialization_functions.he import He

# Your SequentialModel class here...

# Testing
np.random.seed(0)  # For reproducibility

# Create dummy data
X = np.random.randn(100, 3)
y = np.random.randn(100, 1)
X_val = np.random.randn(20, 3)
y_val = np.random.randn(20, 1)

optimizer = AdaptiveMomentEstimation()
loss = MeanSquaredError()
initializer = He()

# Initialize model and components
model = SequentialModel()
model.add(Dense(n_units = 5, 
                input_dim = 3,
                activation = Sigmoid(),
                has_bias = True                 
                ))
model.add(Dense(n_units=5, 
                input_dim=1,
                activation = Linear(),
                has_bias = True
                ))


# Compile and fit the model
model.compile(optimizer, loss, initializer, X)
model.fit(X, y, epochs=10, batch_size=20, X_val=X_val, y_val=y_val, verbose=True)

model.best_params
# Ensure to check the predictions, loss values, and best parameters during and after training.


on layer 1 the output is: [[0.35901725 0.84521284 0.43808681 0.60137579 0.96979654]
 [0.13989344 0.98868656 0.15482258 0.13218146 0.44104607]
 [0.73368552 0.6549913  0.2960759  0.39343212 0.60220731]
 [0.21811769 0.52686905 0.74400263 0.80117505 0.97115762]
 [0.46064401 0.65997853 0.47228287 0.55038212 0.822745  ]
 [0.05432435 0.89891334 0.56042197 0.4040085  0.51308736]
 [0.98516811 0.48432    0.05158391 0.05828666 0.00385863]
 [0.30183746 0.86171003 0.31835852 0.26013325 0.26544433]
 [0.98948761 0.52439962 0.09113207 0.33545912 0.80806557]
 [0.00922044 0.78864434 0.89577906 0.82705862 0.9670374 ]
 [0.50604864 0.70081278 0.32262177 0.26723503 0.14464842]
 [0.34871193 0.1053176  0.81047321 0.70369196 0.24721301]
 [0.1814569  0.93279661 0.32787477 0.29284444 0.5573217 ]
 [0.96364264 0.24159078 0.17873191 0.20405908 0.02853126]
 [0.00756986 0.75433652 0.84412222 0.49455064 0.12212165]
 [0.85652198 0.10542448 0.61247602 0.73546537 0.76450079]
 [0.54929038 0.20366507 0.57370109 0.4056536  

ValueError: operands could not be broadcast together with shapes (5,5) (3,5) 